iCal feeds config, parser, and item
State-of-Rhode-Island-eCMS/ecms_profile pull request #216
Opened 2021-02-01 17:50 UTC by jordan-caldwell

## Summary
This PR adds a custom iCal parser included in a custom module ecms_feeds. This also includes the necessary config to add the feed type to existing ecms_event feature package.

## Metadata

| Question | Answer |
|----------|--------|
| Did you use a meaningful pull request title? | yes
| Did you apply meaningful labels to the pull request? | yes
| Did you perform a self review first? | yes
| `CHANGELOG` reflects changes? | yes
| Did you perform browser testing? | no
| Risk level | Low
| Relevant links | https://thinkoomph.jira.com/browse/RIG-251

2021-02-02 18:37 UTC, jordan-caldwell commented
@ben-hamelin This is out of WIP and ready for review.

2021-02-04 14:30 UTC, ben-hamelin requested changes
just one minor addition

2021-02-04 14:30 UTC, ben-hamelin commented on ecms_base/features/custom/ecms_event/config/install/field.field.node.event.feeds_item.yml
> +translatable: true
should this be translatable false?

2021-02-04 14:30 UTC, ben-hamelin commented on ecms_base/modules/custom/ecms_feeds/src/Feeds/Item/EcmsIcalItem.php
> +
add `declare(strict_types = 1);`

2021-02-05 16:56 UTC, ben-hamelin commented
Ok!
/approved

2021-02-05 17:31 UTC, merged