Introduce publishing workflows configuration and modules
State-of-Rhode-Island-eCMS/ecms_profile pull request #5
Opened 2020-09-02 18:27 UTC by ben-hamelin

## Summary

## Metadata

| Question | Answer |
|----------|--------|
| Did you use a meaningful pull request title? | yes
| Did you apply meaningful labels to the pull request? | yes
| Did you perform a self review first? | yes
| Documentation reflects changes? | yes
| `CHANGELOG` reflects changes? | yes
| Unit/Functional tests reflect changes? | no
| Did you perform browser testing? | yes
| Risk level | Medium
| Relevant links | JIRA issue, bug reports, security alerts, etc.

2020-09-03 13:24 UTC, pfrilling requested changes
There is a lot of configuration here that should be either managed by features or doesn't need to be included. 

I think we should piece meal out each content type and make a PR for a feature module with the necessary configuration included for that content type. Then, the profile just needs to install the feature module and all of the configuration will install.

2020-09-03 13:24 UTC, pfrilling commented on ecms_base/config/install/openid_connect.settings.generic.yml
> +enabled: false
These OIDC configuration needs to be reverted.

2020-09-03 13:24 UTC, pfrilling commented on ecms_base/config/install/openid_connect.settings.facebook.yml
> +enabled: false
The OIDC configuration doesn't need to be installed here.

2020-09-03 13:24 UTC, pfrilling commented on ecms_base/config/install/search.page.node_search.yml
> +langcode: en
I don't think we need to include the core search configuration here.

2020-09-03 13:24 UTC, pfrilling commented on ecms_base/config/install/user.settings.yml
> -register: admin_only
This needs to remain admin_only

2020-09-03 20:30 UTC, pfrilling commented
@ben-hamelin, I created a new PR that I _believe_ is a better approach at getting the content types setup as features. See #7.

2020-09-08 13:40 UTC, ben-hamelin commented
Closing this in favor of features PRs.

2020-09-08 13:40 UTC, closed without merging