Promotion config changes
State-of-Rhode-Island-eCMS/ecms_profile pull request #94
Opened 2020-11-02 22:17 UTC by jordan-caldwell

## Summary
This PR contains two different sets of work relating to the promotion content type.

**First:**
Removed Promotional Image config and added it back fresh. There was a collision with the source field: media_field_image_1 with the event content type. This was causing the install to error out and prevented images from being added to promotions.

**Second:**
Began incorporating work for the new promotion theming and placement. This includes:
- Add Global Display boolean field
- Add Display Title boolean field
- Add view to filter promotions who are not displayed globally.
- Changed body text field to be plain text.

**Install Recommendations:**
Since none of the sites have any promotions to this point I think we should delete both the promotion content type and promotional image media item using the site admin before deploying this change. I was unable to smoothly update the source reference field on my local without doing a fresh install.

## Metadata
| Question | Answer |
|----------|--------|
| Did you use a meaningful pull request title? | yes
| Did you apply meaningful labels to the pull request? | yes
| Did you perform a self review first? | yes
| `CHANGELOG` reflects changes? | yes
| Did you perform browser testing? | no
| Risk level | High
| Relevant links | https://thinkoomph.jira.com/browse/RIG-67

2020-11-02 22:36 UTC, ben-hamelin requested changes
Couple notes on the translation settings. Overall this looks good to me, we can discuss options for the deploy.

2020-11-02 22:36 UTC, ben-hamelin commented on ecms_base/features/custom/ecms_promotions/config/install/field.storage.node.field_promotion_global_display.yml
> +translatable: true
This should be translatable false.

2020-11-02 22:36 UTC, ben-hamelin commented on ecms_base/features/custom/ecms_promotions/config/install/field.storage.node.field_promotion_display_title.yml
>  translatable: true
This should be translatable false

2020-11-03 12:59 UTC, pfrilling reviewed
I think it looks good once Ben's changes have been addressed.

2020-11-03 13:19 UTC, ben-hamelin commented
/approved

2020-11-03 13:34 UTC, merged